version: "3"
services:
  techcode-homepage:
    image: techcode-homepage:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: techcode-homepage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webappfrontend.rule=Host(`home.techcode.cloud`)"
      - "traefik.http.routers.webappfrontend.entrypoints=web"
      - "traefik.http.services.webappfrontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_webgateway"
    networks:
      - traefik_webgateway
    ports:
      - "3000:3000"
networks:
  traefik_webgateway:
    external: true