version: "3"

services:
  techcode-homepage:
    image: techcode-homepage:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: techcode-homepage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.techcode.rule=Host(`techcode.cloud`)"
      - "traefik.http.routers.techcode.entrypoints=web"
      - "traefik.http.services.techcode.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_webgateway"

      - "traefik.http.routers.techcode-https.rule=Host(`techcode.cloud`)"
      - "traefik.http.routers.techcode-https.entrypoints=websecure"
      - "traefik.http.routers.techcode-https.service=techcode-service"
      - "traefik.http.services.techcode-service.loadbalancer.server.port=443"
      - "traefik.http.routers.techcode-https.tls=true"
    networks:
      - traefik_webgateway

networks:
  traefik_webgateway:
    external: true
